global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # NGINX metrics (if using nginx-prometheus-exporter)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 10s

  # Auth Service metrics
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # User Service metrics
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8081']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Product Service metrics
  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:8082']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Docker metrics (optional)
  - job_name: 'docker'
    static_configs:
      - targets: ['docker.for.mac.localhost:9323']
    scrape_interval: 30s
